### ISSUE TITLE
Read the SDA51 through the MUX

### ISSUE THREAD

**Issue by MaximilianoGarcia716** [GenericLab/CO2-soil-respiration-chamber#1]
The MUX and the WEMOS recognize the SDA51, now the WEMOS need to read it

**Comment by nanocastro** [comment]
this to read several CO2 sensors with the same device

**Comment by MaximilianoGarcia716** [comment]
The sensors can be readed through the multiplexer. The code is getting more compact and modular.

**Comment by MaximilianoGarcia716** [comment]
Can be seen resolved in file CO2-soil-respiration-chamber/software/ESP32-S2/WEMOS-lolin32_Multiplexing_SCD41/
