### ISSUE TITLE
Calculate the supported and used current of the devices

### ISSUE THREAD

**Issue by MaximilianoGarcia716** [GenericLab/CO2-soil-respiration-chamber#10]
Calculate the supported current of the wemos lolin32 liteand the USB cable. Also is necesary to estimate the charge usage of all the devices to avoid electrical issues.

**Comment by MaximilianoGarcia716** [comment]
Used current calculated, yet not uploaded

**Comment by nanocastro** [comment]
hola Maxi. porfa empecemos a completar esto con links fotos o lo que haga falta para que se entienda. si es en castellano no importa mientras este

**Comment by MaximilianoGarcia716** [comment]
Added in:
https://github.com/GenericLab/CO2-soil-respiration-chamber/blob/main/hardware/WEMOS-lolin32_Multiplexing_SCD41%20schematics/Terminals%20Count.xlsx
