### ISSUE TITLE
Add a CO2 sensor calibration routine 

### ISSUE THREAD

**Issue by nanocastro** [GenericLab/CO2-soil-respiration-chamber#2]
CO2 sensors are usually calibrated in an open environment atmosphere and the co2 concentration is supposed to be 400ppm. 
We don't need a precise absolute value because in respiration we are looking at relative values but we need to think of a way to enter calibration mode (extra button...?) and a protocol. I think the easiest solution is to enter calibration mode and then put all sensors at once in free air for a while (5min/10 mins) and then store the last value (or make a median of the few last values)

**Comment by MaximilianoGarcia716** [comment]
The calibration routine is ready, it is entered when push the calibration button and use the calibration algorithm suggested by the datasheet

**Comment by MaximilianoGarcia716** [comment]
Can be seen resolved in CO2-soil-respiration-chamber/software/ESP32-S2/WEMOS-lolin32_Multiplexing_SCD41/
