### ISSUE TITLE
CO2 sensor altitude setting

### ISSUE THREAD

**Issue by nanocastro** [GenericLab/CO2-soil-respiration-chamber#3]
We need to be sure to set the right altitude to all CO2 sensors. See [datasheet](https://sensirion.com/products/catalog/SCD42/) for this. Maybe this also needs a reoutine to be changed if the sensors/device change location but for the moment we can add it directly to the code

**Comment by MaximilianoGarcia716** [comment]
Can be seen resolved in CO2-soil-respiration-chamber/software/ESP32-S2/WEMOS-lolin32_Multiplexing_SCD41/

**Comment by MaximilianoGarcia716** [comment]
Can be seen resolved in CO2-soil-respiration-chamber/software/ESP32-S2/WEMOS-lolin32_Multiplexing_SCD41/
