### ISSUE TITLE
Add documentation to code and to readme

### ISSUE THREAD

**Issue by MaximilianoGarcia716** [GenericLab/CO2-soil-respiration-chamber#6]
Add documetation to the code in form of comments and add info in the readme in form of images and explanations.

**Comment by MaximilianoGarcia716** [comment]
Code is more commented than before, not step by step, but commented at least to tell what every function does

**Comment by nanocastro** [comment]
vayamos pensando en hacer un readme que explique el diseño general, workflow, librerias etc. podemos hacer un markdown y dp subirlo o como prefieran  
esta bueno que no esperen a terminar para subirlo. si lo linkean aca todes podemos ir colaborando   
@Santi-Uriguen estemos atentos a ir haciendo esto con todos los experimentos que hagamos

**Comment by MaximilianoGarcia716** [comment]
Code is commented, working on readme.md

**Comment by MaximilianoGarcia716** [comment]
Readme ready

**Comment by MaximilianoGarcia716** [comment]
Add workflow and libraries
