### ISSUE TITLE
Create a chassis and cable blueprint

### ISSUE THREAD

**Issue by MaximilianoGarcia716** [GenericLab/CO2-soil-respiration-chamber#9]
It is needed to create a chassis and cable blueprint to create the conexions and layout of the devices.

**Comment by nanocastro** [comment]
suban aca lo que han hecho, lista de materiales, fotos y si hay diseños tambien (stl y editables)

**Comment by nanocastro** [comment]
estaría bueno también preparar el segundo recipiente. una sugerencia para el adaptador de la tapa 
![imagen](https://github.com/GenericLab/CO2-soil-respiration-chamber/assets/23299935/78cdaf3a-4085-48f8-a239-4e6f27f3afed)

**Comment by MaximilianoGarcia716** [comment]
Ya subimos al repositorio el diagrama del circuito, está en el enlace:
https://github.com/GenericLab/CO2-soil-respiration-chamber/blob/main/hardware/WEMOS-lolin32_Multiplexing_SCD41%20schematics/Lolin%20Multiplexing.png
